export const routes = {
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  profile: '/profile',
  orders: '/orders',
  home: '/',
  payment: '/payment',
  products: '/products',
  product_id: '/products/:id',
  collections: '/collections',
  rooms: '/rooms',
  cart: '/cart',
  wishlish: '/wishlish',
  verify_email: '/verify-email',
  change_password: '/change-password',
  update_profile: '/update-profile',
}
