export { default as SellerLogin } from './Auth/Login'
export { default as SellerSignup } from './Auth/Signup'
export { default as SellerHome } from './Home/SellerHome'
export { default as OrdersManagement } from './Orders/OrdersManagement'
export { default as ProductsManagement } from './Products/ProductsManagement'
