export const Seller_QueryKeys = {
  USER_PROFILE: 'USER_PROFILE',
  USER_EDIT: 'USER_EDIT',
  SHOP_INFO: 'SHOP_INFO',
  SHOP_PROFILE: 'SHOP_PROFILE',
  SHOP_CATEGORY: 'SHOP_CATEGORY',
  SHOP_PRODUCTS: 'SHOP_PRODUCTS',
  DISTRICTS: 'DISTRICTS',
  COMMUNES: 'COMMUNES',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  SYSTEM_CATEGORY: 'SYSTEM_CATEGORY',
  SHOP_VOUCHER: 'SHOP_VOUCHER',
}

export const Buyer_QueryKeys = {
  SHOP_PROFILE: 'SHOP_PROFILE',
  SHOP_CATEGORIES: 'SHOP_CATEGORIES',
  USER_PROFILE: 'USER_PROFILE',
  USER_ADDRESS: 'USER_ADDRESS',
}
