export const QueryKeys = {
  USER_PROFILE: 'USER_PROFILE',
  USER_EDIT: 'USER_EDIT',
  SHOP_INFO: 'SHOP_INFO',
  SHOP_CATEGORY: 'SHOP_CATEGORY',
  SHOP_PRODUCTS: 'SHOP_PRODUCTS',
  DISTRICTS: 'DISTRICTS',
  COMMUNES: 'COMMUNES',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
}
