export const Seller_QueryKeys = {
  USER_PROFILE: 'USER_PROFILE',
  USER_EDIT: 'USER_EDIT',
  SHOP_INFO: 'SHOP_INFO',
  SHOP_PROFILE: 'SHOP_PROFILE',
  SHOP_CATEGORY: 'SHOP_CATEGORY',
  SHOP_PRODUCTS: 'SHOP_PRODUCTS',
  DISTRICTS: 'DISTRICTS',
  COMMUNES: 'COMMUNES',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  SYSTEM_CATEGORY: 'SYSTEM_CATEGORY',
  SHOP_VOUCHER: 'SHOP_VOUCHER',
}

export const Buyer_QueryKeys = {
  SHOP_PROFILE: 'SHOP_PROFILE',
  SHOP_CATEGORIES: 'SHOP_CATEGORIES',
  USER_PROFILE: 'USER_PROFILE',
  USER_ADDRESS: 'USER_ADDRESS',
  USER_WISHLIST: 'USER_WISHLIST',
  VOUCHER_BY_PRODUCT: 'VOUCHER_BY_PRODUCT',
  GET_WALLET: 'GET_WALLET',
  ORDER_LIST: 'ORDER_LIST',
  ORDER_DETAIL: 'ORDER_DETAIL',
  FOLLOWING_PEOPLE: 'FOLLOWING_PEOPLE',
  SEARCH_BY_KEYWORD: 'SEARCH_BY_KEYWORD',
  SYSTEM_CATEGORY: 'SYSTEM_CATEGORY',
  LIST_USER_SENT_MESSAGE: 'LIST_USER_SENT_MESSAGE',
}
