export const buyer_routes = {
  buyer: 'buyer',
  login: '/buyer/login',
  shop_home: '/shop/:id',
  signup: '/buyer/signup',
  confirm_email: '/buyer/confirm-email',
  account: '/buyer/account',
  cart: 'buyer/cart',
  search: '/search/:keyword',
  checkout: 'buyer/checkout',
  mall: '/mall',
  products: '/products',
  about: '/about',
  chat_gpt: '/chat-gpt',
  product_detail: '/product/:id',
  whishlist: 'buyer/whishlist',
  profile: 'buyer/account/profile',
  purchase: 'purchase',
  order_detail: 'purchase/order/:id',
  review_product: 'purchase/review-product/:id',
  address: 'address',
  wallet: 'wallet',
  verify: 'verify-email',
  voucher: 'vouchers',
  notifications_order: 'notifications/order',
  notifications_voucher: 'notifications/voucher',
  notifications_account: 'notifications/account',
  change_password: 'change-password',
}

export const seller_routes = {
  seller: 'seller',
  login: '/seller/login',
  signup: '/seller/signup',
  forgot_password: '/seller/forgot-password',
  confirm_email: '/seller/confirm-email',
  orders: 'orders',
  vnpay_return: 'vnpay-return',
  orders_unpaid: 'unpaid',
  orders_toship: 'toship',
  orders_shipping: 'shipping',
  orders_shipped: 'shipped',
  orders_compelted: 'completed',
  orders_cacelled: 'cancelled',
  orders_return: 'return',
  orders_failed_delivery: 'failed_delivery',
  products: 'products',
  add_product: 'products/new',
  update_product: 'products/update/:id',
  product_banned: 'products/banned',
  product_brand: 'products/brand',
  marketing: 'marketing',
  discount_marketing: 'marketing/discount',
  shop_flashsale: 'marketing/shop-flash-sale',
  shop_campain: 'marketing/campaign',
  income: 'income',
  payment_account: 'income/payment-account',
  bank_list: 'income/bank-list',
  chat: 'chat',
  feedback: 'feedback',
  shop: 'shop',
  shop_cagory: 'category',
  shop_address: 'shop/address',
  settings: 'settings',
  setting_shop: 'shop',
  setting_profile: 'profile',
  setting_vat: 'vat',
  setting_identify: 'identify',
  setting_shop_rating: 'settings/shop/rating',
  setting_category: 'settings/shop/category',
  notify: 'notify',
}

export const common_routes = {
  vnpay_return: 'vnp-return',
}
