export const buyer_routes = {
  buyer: 'buyer',
  login: '/buyer/login',
  signup: '/buyer/signup',
  confirm_email: '/buyer/confirm-email',
  account: '/buyer/account',
  cart: '/cart',
  whishlist: '/whishlist',
  profile: 'buyer/account/profile',
  purchase: 'purchase',
  order_detail: 'purchase/order/:id',
  address: 'address',
  verify: 'verify-email',
  voucher: 'vouchers',
  notifications_order: 'notifications/order',
  change_password: 'change-password',
}

export const seller_routes = {
  seller: 'seller',
  login: '/seller/login',
  signup: '/seller/signup',
  confirm_email: '/seller/confirm-email',
  orders: 'orders',
  orders_unpaid: 'unpaid',
  orders_toship: 'toship',
  orders_shipping: 'shipping',
  orders_shipped: 'shipped',
  orders_compelted: 'completed',
  orders_cacelled: 'cancelled',
  orders_return: 'return',
  orders_failed_delivery: 'failed_delivery',
  products: 'products',
  add_product: 'products/new',
  product_banned: 'products/banned',
  product_brand: 'products/brand',
  marketing: 'marketing',
  discount_marketing: 'marketing/discount',
  shop_flashsale: 'marketing/shop-flash-sale',
  shop_campain: 'marketing/campaign',
  income: 'income',
  chat: 'chat',
  shop: 'shop',
  shop_address: 'shop/address',
  settings: 'settings',
  setting_shop: 'shop',
  setting_profile: 'profile',
  setting_vat: 'vat',
  setting_identify: 'identify',
  setting_shop_rating: 'settings/shop/rating',
  setting_category: 'settings/shop/category',
}
